import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  district(){
    return [
      {
        id:1,
        name:"cuddalore"
      },
      {
        id:2,
        name:"Trichy"
      },
      {
        id:3,
        name:"Salem"
      },
      {
        id:4,
        name:"coimbatore"
      },
      {
        id:5,
        name:"madurai"
      },
    ]
  }
  taluk(){
    return[
      {
        id:1,
        name:"virudhachalam"
      },
      {
        id:1,
        name:"chidambaram"
      },
      {
        id:1,
        name:"tittakudi"
      },
      {
        id:2,
        name:"srirangam"
      },
      {
        id:2,
        name:"manapparai"
      },
      {
        id:2,
        name:"lalgudi"
      },
      {
        id:3,
        name:"Attur"
      },
      {
        id:3,
        name:"Metur"
      },
      {
        id:3,
        name:"valapadi"
      },
      {
        id:4,
        name:"perur"
      },
      {
        id:4,
        name:"pollachi"
      },
      {
        id:4,
        name:"madukkarai"
      },
      {
        id:5,
        name:"Melur"
      },
      {
        id:5,
        name:"Vadipatti"
      },
      {
        id:5,
        name:"Peraiyur"
      },
    ]
  }
  village(){
    return[
      {
        name:"virudhachalam",
        num:"Agaram"
      },
      {
        name:"virudhachalam",
        num:"mangalampet"
      },
      {
        name:"virudhachalam",
        num:"periyakurichi"
      },
      {
        name:"chidambaram",
        num:"Agaram"
      },
      {
        name:"chidambaram",
        num:"mangalampet"
      },
      {
        name:"chidambaram",
        num:"periyakurichi"
      },
      {
        name:"tittakudi",
        num:"Agaram"
      },
      {
        name:"tittakudi",
        num:"mangalampet"
      },
      {
        name:"tittakudi",
        num:"periyakurichi"
      },
      {
        name:"srirangam",
        num:"Allur"
      },
      {
        name:"srirangam",
        num:"palur"
      },
      {
      name:"srirangam",
      num:"alundur"
      },
      {
        name:"manapparai",
        num:"aniyappur"
      },
      {
        name:"manapparai",
        num:"karuppur"
      },
      {
        name:"manapparai",
        num:"athampatti"
      },
      {
        name:"Lalgudi",
        num:"orathur"
      },
      {
        name:"lalgudi",
        num:"malvoy"
      },
      {
        name:"lalgudi",
        num:"neikulam"
      },
      {
        name:"Attur",
        num:"paithur"
      },
      {
        name:"Attur",
        num:"kothampadi"
      },
      {
        name:"Attur",
        num:"pungavadi"
      },
      {
        name:"Metur",
        num:"amaram"
      },
      {
        name:"Metur",
        num:"koppam"
      },
      {
        name:"Metur",
        num:"aranganur"
      },
      {
        name:"valapadi",
        num:"anuppur"
      },
      {
        name:"valapadi",
        num:"kurichi"
      },
      {
        name:"valapadi",
        num:"veppur"
      },
      {
        name:"perur",
        num:"ikkarai"
      },
      {
        name:"perur",
        num:"pasur"
      },
      {
        name:"perur",
        num:"kuppanur"
      },
      {
        name:"pollachi",
        num:"achipatti"
      },
      {
        name:"pollachi",
        num:"kulathur"
      },
      {
        name:"pollachi",
        num:"kplarpatti"
      },
      {
        name:"madukkarai",
        num:"Pichanur"
      },
      {
        name:"madukkarai",
        num:"palathurai"
      },
      {
        name:"madukkarai",
        num:"seerapalayam"
      },
      {
        name:"melur",
        num:"Amoor"
      },
      {
        name:"melur",
        num:"Nalukulam"
      },
      {
        name:"melur",
        num:"ekkipatti"
      },
      {
        name:"Vadipatti",
        num:"Alagapuri"
      },
      {
        name:"Vadipatti",
        num:"Irumbadi"
      },
      {
        name:"Vadipatti",
        num:"Errampatti"
      },
      {
        name:"Peraiyur",
        num:"Vandari"
      },
      {
        name:"Peraiyur",
        num:"Velambur"
      },
      {
        name:"Peraiyur",
        num:"Thirumanickam"
      },

    ]
  }
}



